### PR TITLE
add waveform and support scrubbing

### LINKED ISSUE #1: Handle Scrubbing (Touch)
At the moment if you go to https://wav.zbd.gg/track/75ba6880-cf73-4f26-9474-577d96627081 you can easily start and pause/stop the song from playing. But you cannot choose a specific part of the song to play by scrubbing left and right on the track like you can on apps such as spotify/youtube/apple music/etc.

This ticket is to handle this scrubbing feature on this module. This improved module should allow the user to drag the song play time location, and when it is unfocused/let-go, the song should quickly reload and then begin playing at that specific time in the song duration.

This iframe is only EVER rendered in a mobile environment so this needs to repsond really well to MOBILE TOUCH events. Please test accordingly.

### LINKED ISSUE #3: Show audioform behind scrubber
We want to add a soundform behind/above the player such that it renders similar to how it looks on soundcloud.com. Use a library/decoder/etc to understand the song and then provide the soundwave display. As the song plays, the displays gets `filled in` in the same way it does in Soundcloud.com.

Screenshot 2023-08-07 at 12 13 11 AM

### PR DESCRIPTION
**Pull request by mnmt7**
fixes #1
fixes #3 

Video: https://jam.dev/c/0f243c9f-9f98-4c6b-94d4-f007b7afa61e

/claim #1
/claim #3

### CODE REVIEW

**Comment by andrerfneves** [comment]
@mnmt7 thanks for submitting the PR.

I just approved the deployment of this PR to Vercel so we can test it. But testing locally didn't yield the same results as your video for some reason.

`http://localhost:3003/track/75ba6880-cf73-4f26-9474-577d96627081`

Screenshot 2023-08-13 at 8 35 38 PM

**Comment by andrerfneves** [comment]
It does seem to work on the Preview site...

https://wavlake-zbd-git-fork-mnmt7-scrubbing-and-audioform-zbd.vercel.app/track/b66d8b6c-686d-45e0-804a-1881b9b519ce

And then again sometimes for some songs it doesnt?

https://wavlake-zbd-git-fork-mnmt7-scrubbing-and-audioform-zbd.vercel.app/track/729ff127-1fcc-4086-8e67-4386e87ac585

Also is this a setting in the waveform builder? this song for example ALL of the bars are almost at the very top. Can we ease that a little bit if there's a setting for it?

Screenshot 2023-08-13 at 8 38 23 PM

**Comment by andrerfneves** [comment]
@mnmt7 any thoughts?

**Comment by mnmt7** [comment]
@andrerfneves It is due to the CORS error. Make sure that server from which the audio is being fetched sends the necessary CORS headers. I tried using [CORS Anywhere](https://github.com/Rob--W/cors-anywhere) and it worked.

Screenshot from 2023-08-19 17-39-08

**Comment by mnmt7** [comment]
@andrerfneves any updates?

**Comment by andrerfneves** [comment]
hey @mnmt7 I'm in touch with the Wavlake folks to figure out this CORS issue. I'm going to consider this complete and award the bounty.

**Pull request merged**
